# Generated by Django 5.2.8 on 2026-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_108", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectioncategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
