# Generated by Django 5.2.8 on 2026-03-16 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_108", "0002_inspectioncategory_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raised_108_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_remarked",
            field=models.BooleanField(
                default=False,
                help_text="True if this was previously raised by someone else/past turn",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="item_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the question or category for easy DB identification",
                max_length=255,
                null=True,
            ),
        ),
    ]
