# Generated by Django 5.2.8 on 2026-02-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_alter_district_id_alter_inspection_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecode",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_codes",
                to="authentication.project",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="authentication.project",
            ),
        ),
    ]
