# Generated by Django 5.2.8 on 2026-02-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_servicecode_project_vehicle_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_notifications",
                to="authentication.project",
            ),
        ),
    ]
