# Generated by Django 5.2.8 on 2026-02-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_notification_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRoleDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_deadline_days",
                    models.IntegerField(
                        default=1,
                        help_text="Days allowed before inspection is considered missed.",
                    ),
                ),
                (
                    "inspection_deadline_hours",
                    models.IntegerField(
                        default=0, help_text="Additional hours allowed."
                    ),
                ),
                (
                    "inspection_deadline_minutes",
                    models.IntegerField(
                        default=0, help_text="Additional minutes allowed."
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_deadlines",
                        to="authentication.project",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_deadlines",
                        to="authentication.role",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "role")},
            },
        ),
    ]
