# Generated by Django 5.2.8 on 2026-02-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scheduler_hour',
            field=models.IntegerField(default=10, help_text='Hour of the day to check deadlines (0-23)'),
        ),
        migrations.AddField(
            model_name='project',
            name='scheduler_minute',
            field=models.IntegerField(default=0, help_text='Minute of the hour to check deadlines (0-59)'),
        ),
    ]
