# Generated by Django 5.2.8 on 2026-03-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_apikey_apikeyhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginrecord",
            name="logout_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
