# Generated by Django 5.2.8 on 2026-02-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_104", "0006_inspectioncategory_manager_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ops_104.inspectionquestion",
            ),
        ),
    ]
