# Generated by Django 5.2.8 on 2026-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_104", "0007_complaint_tracking_id_alter_complaint_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="closure_remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
