# Generated by Django 5.2.8 on 2026-03-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_104", "0010_complaint_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="item_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the question or category for easy DB identification",
                max_length=255,
                null=True,
            ),
        ),
    ]
