# Generated by Django 5.2.8 on 2026-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_104", "0011_complaint_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="is_remarked",
            field=models.BooleanField(
                default=False,
                help_text="True if this was previously raised by someone else/past turn",
            ),
        ),
    ]
