# Generated by Django 5.2.8 on 2026-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erc_104", "0003_ercgridsection_total_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="erccategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
